source "http://rubygems.org"
gem 'nokogiri', '1.6.1'
gem 'cucumber'
gem 'capybara'
gem 'bddfire', "1.9.4"
gem 'selenium-webdriver'
gem 'poltergeist'
gem 'rake'
gem 'yard-cucumber'
gem 'redcarpet'
gem 'rubocop'
gem 'cuke_sniffer'
gem 'json', "1.5.5"
gem 'rspec'
gem 'relish'
gem 'rubocop-checkstyle_formatter'
gem "parallel_tests"
gem "chromedriver-helper", "0.0.6"
#gem "websocket-driver", "1.2.2"
